# gpu-next is mandatory for HDR - the old `gpu` vo doesn't support it
vo=gpu-next
gpu-api=vulkan

target-colorspace-hint-mode=source

# Hardware decoding - vaapi is the right one for RDNA3 on Linux
hwdec=vaapi
hwdec-codecs=all

# General quality stuff
deband=yes
dither-depth=auto


#panscan for ultrawide
panscan=0.9
