flatpak "com.dec05eba.gpu_screen_recorder"
flatpak "com.valvesoftware.Steam"
flatpak "com.vysp3r.ProtonPlus"
flatpak "dev.vencord.Vesktop"
flatpak "io.github.Foldex.AdwSteamGtk"
flatpak "io.github.ilya_zlobintsev.LACT"
flatpak "net.pcsx2.PCSX2"
flatpak "org.DolphinEmu.dolphin-emu"
