[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
themes-dir = "scripts"
hook = ". %f"
#yazi
[[items]]
path = "https://github.com/tinted-theming/tinted-yazi"
name = "tinted-yazi"
themes-dir = "flavors"
hook = '''
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.config/yazi/flavors/tinted-scheme.yazi/flavor.toml"
'''
#lazygit
[[items]]
name = "tinted-lazygit"
path = "https://github.com/tinted-theming/tinted-lazygit"
themes-dir = "themes"
supported-systems = ["base16"]

#Claude Code
[[items]]
name = "tinted-claude-code"
path = "https://github.com/tinted-theming/tinted-claude-code"
themes-dir = "scripts"
theme-file-extension = ".js"
supported-systems = ["base16", "base24", "tinted8"]
hook = "mkdir -p \"$HOME/.claude/themes\" && node \"$TINTY_THEME_FILE_PATH\" > \"$HOME/.claude/themes/tinty.json\""

#kitty
#[[items]]
#path = "https://github.com/tinted-theming/tinted-terminal"
#name = "tinted-terminal"
#themes-dir = "themes/kitty"
#hook = "kill -USR1 $(pgrep -x kitty)"
#supported-systems = ["base16", "base24"]

#Ghostty
[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/ghostty"
# With `theme` set to "tinted-theming", this will be where Ghostty looks for the theme file:
hook = """
mkdir -p ~/.config/ghostty/themes
command cp -f "$TINTY_THEME_FILE_PATH" ~/.config/ghostty/themes/tinted-theming
killall -SIGUSR2 ghostty 2>/dev/null || true
"""
supported-systems = ["base16", "base24"]

#gowall
[[items]]
path = "https://github.com/tinted-theming/tinted-gowall"
name = "wallpaper"
themes-dir = "themes" 
supported-systems = ["base16", "base24"]

#Steam millennium material
[[items]]
path = "https://github.com/GooseRooster/tinted-material-millennium"
name = "tinted-material-millennium"
themes-dir = "output"
hook = "cp \"$TINTY_THEME_FILE_PATH\" ~/.steam/steam/steamui/skins/Material-Theme/css/main/colors/matugen.css"
supported-systems = ["base16"]

#Vesktop (Discord)
[[items]]
path = "https://github.com/deathbeam/base16-discord.git"
name = "base16-discord"
themes-dir = "themes"
theme-file-extension = ".theme.css"
supported-systems = ["base16"]
hook = "cp \"$TINTY_THEME_FILE_PATH\" \"$HOME/.config/vesktop/settings/quickCss.css\""

#Zen
[[items]]
path = "https://github.com/GooseRooster/base16-tinted-zen"
name = "base16-tinted-zen"
themes-dir = "output"
hook = "cp \"$TINTY_THEME_FILE_PATH\" \"$HOME/.var/app/app.zen_browser.zen/.zen/$(ls ~/.var/app/app.zen_browser.zen/.zen | grep -i 'release' | head -1)/chrome/userChrome.css\""
supported-systems = ["base16"]
